backtest:
  n_folds: 3
  n_jobs: 1
  metrics:
  - _target_: etna.metrics.MAE
  - _target_: etna.metrics.MSE
  - _target_: etna.metrics.MAPE
  - _target_: etna.metrics.SMAPE
  - _target_: etna.metrics.R2
pipeline:
  _target_: etna.pipeline.Pipeline
  horizon: 14
  model:
    _target_: etna.models.NaiveModel
    lag: ${lag}
  transforms: ['${preprocessing}']
preprocessing: null
add_const_transform_value: null
lag: null